### ISSUE TITLE
Installation of  V 0.0.38

### ISSUE THREAD

**Issue by LGO44** [msp1974/wiserHeatAPIv2#27]
@msp1974  - feed back for the installation of this version
Installation of the dev version:

![Capture d’écran 2022-07-19 à 17 23 48](https://user-images.githubusercontent.com/95585425/179788527-231f3dde-7504-4ef0-a9d0-e16cc619d05a.png)

![image](https://user-images.githubusercontent.com/95585425/179789033-a71ce927-b8cf-47e5-abe5-9ceab77b92d2.png)

Extract of the logs:

ERROR: No matching distribution found for wiserHeatAPIv2==0.0.38
2022-07-19 17:16:39 ERROR (MainThread) [homeassistant.setup] Setup failed for custom integration wiser: Requirements for wiser not found: ['wiserHeatAPIv2==0.0.38'].
2022-07-19 17:16:40 ERROR (MainThread) [homeassistant] Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/discovery_flow.py", line 74, in _async_process_pending_flows
    await gather_with_concurrency(
  File "/usr/src/homeassistant/homeassistant/util/async_.py", line 199, in gather_with_concurrency
    return await gather(
  File "/usr/src/homeassistant/homeassistant/util/async_.py", line 197, in sem_task
    return await task
  File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 222, in async_init
    flow, result = await task
  File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 240, in _async_init
    flow = await self.async_create_flow(handler, context=context, data=data)
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 779, in async_create_flow
    await async_process_deps_reqs(self.hass, self._hass_config, integration)
  File "/usr/src/homeassistant/homeassistant/setup.py", line 360, in async_process_deps_reqs
    await requirements.async_get_integration_with_requirements(
  File "/usr/src/homeassistant/homeassistant/requirements.py", line 49, in async_get_integration_with_requirements
    return await manager.async_get_integration_with_requirements(domain)
  File "/usr/src/homeassistant/homeassistant/requirements.py", line 168, in async_get_integration_with_requirements
    await self._async_process_integration(integration, done)
  File "/usr/src/homeassistant/homeassistant/requirements.py", line 183, in _async_process_integration
    await self.async_process_requirements(
  File "/usr/src/homeassistant/homeassistant/requirements.py", line 230, in async_process_requirements
    self._raise_for_failed_requirements(name, missing)
  File "/usr/src/homeassistant/homeassistant/requirements.py", line 252, in _raise_for_failed_requirements
    raise RequirementsNotFound(integration, [req])
homeassistant.requirements.RequirementsNotFound: Requirements for wiser not found: ['wiserHeatAPIv2==0.0.38'].

**Comment by msp1974** [comment]
You are very keen Christian! 😀

 I have not finished and released the api update yet - which is what it is complaining about.

I was going to do this this weekend. I'll let you know.  This will have an update to the card to copy days when  editing a schedule, improved diagnostics output method (which is why an api update) and a couple of minor fixes.

**Comment by LGO44** [comment]
Sorry to be so early...
But I saw your job and I was afraid to have missed ...
I have used the schedule card a lot...

**Comment by msp1974** [comment]
Just released 0.0.38 so the v3.1.2 version in Dev branch of Wiser Integration should now install.
